version: "3.4"

services:
  dfclash:
    container_name: dfclash
    image: gdfsnhsw/dfclash:latest
    privileged: true
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    restart: unless-stopped
    volumes:
      - ./clash_config:/clash_config
    environment:
      - TZ=Asia/Shanghai
      - EN_MODE=redir-host
      #- LOCALNETWORK=127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,224.0.0.0/4,172.16.0.0/12
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      dMACvLAN:
        ipv4_address: 192.168.88.2
    dns:
      - 114.114.114.114

networks:
  dMACvLan:
    external:
      name: dMACvLan
