version: "3.4"

services:
  aiclash:
    container_name: aiclash
    image: gdfsnhsw/aiclash:latest
    privileged: true
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    restart: unless-stopped
    volumes:
      - ./clash_config:/clash_config
      - ./subconverter:/etc/subconverter
      - ./mosdns:/etc/mosdns
    environment:
      - TZ=Asia/Shanghai
      - EN_MODE=redir-host
      - ROUTE_MODE=redir-tun
      - GET_CONFIG=true
      - UDP=true
      - URL=https://dler.cloud/aaa|trojan://密码@域名:443#名称
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      dMACvLAN:
        ipv4_address: 192.168.88.2
    dns:
      - 114.114.114.114

networks:
  dMACvLAN:
    external:
      name: _dMACvLan
